server:
  port: 8080



logging:
  level:
    root: info
    cn.zxy: debug
  pattern:
    dateformat: HH:mm:ss.SSS

spring:
  datasource:
    url: jdbc:mysql:/outdb
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

  redis:
    host: 192.168.14.65
    password: 123456
    database: 0
    port: 6379

mybatis-plus:
  global-config:
    banner: on
  mapper-locations: classpath*:mapper/**/*.xml
